apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: s11
  labels:
    app: web-headless
spec:
  serviceName: web-service-headless   # gives pods web-0.web-service-headless... DNS names
  replicas: 3
  selector:
    matchLabels:
      app: web-headless
  template:
    metadata:
      labels:
        app: web-headless
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - name: web
              containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
