# Hello World - Apache HTTP Server
FROM httpd:2.4-alpine

# httpd serves everything in this directory by default
COPY index.html /usr/local/apache2/htdocs/index.html

EXPOSE 80
# Base image already runs httpd in the foreground
