apiVersion: apps/v1
kind: Deployment
metadata:
  name: s20-gitops-web
  labels:
    app: s20-gitops-web
spec:
  replicas: 2            # change this in Git, commit, push -> ArgoCD rolls it out
  selector:
    matchLabels:
      app: s20-gitops-web
  template:
    metadata:
      labels:
        app: s20-gitops-web
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: /, port: 80 }
            periodSeconds: 5
          resources:
            requests: { cpu: 10m, memory: 16Mi }
            limits:   { cpu: 100m, memory: 64Mi }
