apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notes-chart.fullname" . }}-deploy
  labels:
    {{- include "notes-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "notes-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notes-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: notes
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "notes-chart.fullname" . }}-config
          volumeMounts:
            - name: page
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: page
          configMap:
            name: {{ include "notes-chart.fullname" . }}-page
            items:
              - key: index.html
                path: index.html
